import { LabelLevelCriteriaEnum } from '../enum/label-level-criteria.enum'
import { ServiceOfferingLabelLevelMapper } from './service-offering-label-level.mapper'

describe('ServiceOfferingLabelLevelMapper', () => {
  it('should map query result to DTO', async () => {
    const queryResult = {
      criteria: [
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_1_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_1_2_', 'Deny'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_1_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_1_4_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_10_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_2_', 'Not applicable'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_4_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_5_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_6_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_7_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_8_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_2_9_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_3_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_3_2_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_3_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_3_4_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P1_3_5_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_1_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_1_2_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_1_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_2_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_4_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_5_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_6_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_2_7_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_3_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_3_2_', 'Deny'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P2_3_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_10_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_11_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_12_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_13_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_14_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_15_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_16_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_17_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_18_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_19_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_20_', 'Deny'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_2_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_4_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_5_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_6_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_7_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_8_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P3_1_9_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P4_1_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P4_1_2_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_1_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_2_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_3_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_4_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_5_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_6_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_1_7_', 'Confirm'],
        ['_https_registry_lab_gaia_x_eu_development_api_trusted_shape_registry_v1_shapes_jsonld_trustframework_P5_2_1_', 'Confirm']
      ],
      serviceOfferingId:
        '<https://wizard.lab.gaia-x.eu/api/credentials/2d37wbGvQzbAQ84yRouh2m2vBKkN8s5AfH9Q75HZRCUQmJW7yAVSNKzjJj6gcjE2mDNDUHCichXWdMH3S2c8AaDLm3kXmf5R8D5ch6kzdcppz5v33FsigeezVhPyjpwXbkjEbSxGua7dK42e4ohoWNZmCGfk9JFJhdDy3AT4PzVw32tkKQwKkbUDm2qnK7T88S3qQPqXG73Shi48jtJvH7kX7J3zTKjAKgPAae5Q4vRRaPKFwSKu2gzJU8xja5RkYxNRmyXEpfT5K458AnoGMccM5WjQHCWv9zaha1wPbSwPgjdWKBVghFbeZM3mkQ66yi35vahn2D8kV12Njbu1BnxTwsUn8P8Fqrvybx3s1rG7fi53RNiRC2qQ86gR8urG8qjK8jAXpQWMWmvhsrRqdZ2B4pusnopuAPNbtaQZTx3LmKurE1RwnAMeyUsxYAfH6PLVoYSwm8UTcN456JEbjzM7J2uquXzeEbWTdNm94YHoPMBrZZ41wuN2QQcw6rfCL2fsXhpX3Y9qVicr2SdioHRELm1zqjjL5AA2ZJcyWk9hhiXyMiGzZwhE4UyCji7m4QaYP7TgjgxfNR2S6tb1BXrEaehUttNwUXzKfqN#f99c57cc72d83c212177561ba6a21fc505697c61d6a8d9a83c6aebd422c7df82>'
    }

    const dto = ServiceOfferingLabelLevelMapper.map(queryResult)

    expect(dto.serviceOfferingId).toEqual(
      '<https://wizard.lab.gaia-x.eu/api/credentials/2d37wbGvQzbAQ84yRouh2m2vBKkN8s5AfH9Q75HZRCUQmJW7yAVSNKzjJj6gcjE2mDNDUHCichXWdMH3S2c8AaDLm3kXmf5R8D5ch6kzdcppz5v33FsigeezVhPyjpwXbkjEbSxGua7dK42e4ohoWNZmCGfk9JFJhdDy3AT4PzVw32tkKQwKkbUDm2qnK7T88S3qQPqXG73Shi48jtJvH7kX7J3zTKjAKgPAae5Q4vRRaPKFwSKu2gzJU8xja5RkYxNRmyXEpfT5K458AnoGMccM5WjQHCWv9zaha1wPbSwPgjdWKBVghFbeZM3mkQ66yi35vahn2D8kV12Njbu1BnxTwsUn8P8Fqrvybx3s1rG7fi53RNiRC2qQ86gR8urG8qjK8jAXpQWMWmvhsrRqdZ2B4pusnopuAPNbtaQZTx3LmKurE1RwnAMeyUsxYAfH6PLVoYSwm8UTcN456JEbjzM7J2uquXzeEbWTdNm94YHoPMBrZZ41wuN2QQcw6rfCL2fsXhpX3Y9qVicr2SdioHRELm1zqjjL5AA2ZJcyWk9hhiXyMiGzZwhE4UyCji7m4QaYP7TgjgxfNR2S6tb1BXrEaehUttNwUXzKfqN#f99c57cc72d83c212177561ba6a21fc505697c61d6a8d9a83c6aebd422c7df82>'
    )
    expect(dto.criteria).toEqual(
      new Map<LabelLevelCriteriaEnum, string>([
        [LabelLevelCriteriaEnum.P1_1_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_1_2, 'Deny'],
        [LabelLevelCriteriaEnum.P1_1_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_1_4, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_2, 'Not applicable'],
        [LabelLevelCriteriaEnum.P1_2_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_4, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_5, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_6, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_7, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_8, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_9, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_2_10, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_3_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_3_2, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_3_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_3_4, 'Confirm'],
        [LabelLevelCriteriaEnum.P1_3_5, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_1_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_1_2, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_1_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_2, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_4, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_5, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_6, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_2_7, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_3_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P2_3_2, 'Deny'],
        [LabelLevelCriteriaEnum.P2_3_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_2, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_4, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_5, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_6, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_7, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_8, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_9, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_10, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_11, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_12, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_13, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_14, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_15, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_16, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_17, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_18, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_19, 'Confirm'],
        [LabelLevelCriteriaEnum.P3_1_20, 'Deny'],
        [LabelLevelCriteriaEnum.P4_1_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P4_1_2, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_1, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_2, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_3, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_4, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_5, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_6, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_1_7, 'Confirm'],
        [LabelLevelCriteriaEnum.P5_2_1, 'Confirm']
      ])
    )
  })
})
