{{ if .Capabilities.APIVersions.Has "kyverno.io/v1" -}}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ include "gx-compliance.fullname" . }}-policy
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    policies.kyverno.io/title: Verify Image
    policies.kyverno.io/category: Software Supply Chain Security, EKS Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.7.0
    policies.kyverno.io/description: >-
      Using the Cosign project, OCI images may be signed to ensure security is maintained.
      Those signatures can be verified before pulling into a cluster. 
      This policy checks the signature of the image to ensure it has been signed by verifying
      its signature against the provided public key.
spec:
  validationFailureAction: Enforce
  background: true
  generateExisting: true
  rules:
    - name: verify-image
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "registry.gitlab.com/gaia-x/lab/compliance/gx-compliance:*"
          attestors:
            - entries:
                - keyless:
                    subject: "https://gitlab.com/gaia-x/lab/compliance/gx-compliance//.gitlab-ci.yml@refs/*"
                    issuer: "https://gitlab.com"
                    rekor:
                      url: https://rekor.sigstore.dev
{{ end }}